name: JavaScript Code Check & Discord Notifications

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10  # Add timeout to prevent hanging
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1  # Shallow clone for faster checkout
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Cache node modules
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    
    - name: Install dependencies
      run: |
        npm ci --prefer-offline --no-audit
        npm install eslint --save-dev --no-audit
      
    - name: Run ESLint
      run: |
        npx eslint . --ext .js --format stylish > eslint_report.txt || true
        
    - name: Create Issue on Problems
      if: failure()
      uses: actions/github-script@v6
      with:
        script: |
          const fs = require('fs');
          const eslintReport = fs.readFileSync('eslint_report.txt', 'utf8');
          
          if (eslintReport.includes("error") || eslintReport.includes("warning")) {
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '🔍 ESLint Check Results',
              body: `ESLint found issues in the latest commit:
              \`\`\`
              ${eslintReport}
              \`\`\`
              `
            });
          }
          
    - name: Send Results to Discord
      if: always()
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@master
      with:
        args: |
          🔍 Results for ${{ github.repository }}
          Status: ${{ job.status }}
          Commit: ${{ github.sha }}